#ifndef TASK5_STATUS_INDICATOR_BEHAVIOR_BOARDS_H
#define TASK5_STATUS_INDICATOR_BEHAVIOR_BOARDS_H

#include <stdbool.h>
#include <stdint.h>

#define K380_BOOTLOADER_STATUS_INDICATOR 1
#define K380_STATUS_PIXEL_COUNT 4

enum {
  STATE_BOOTLOADER_STARTED = 0,
  STATE_USB_MOUNTED,
  STATE_USB_UNMOUNTED,
  STATE_FACTORY_RESET_STARTED,
  STATE_FACTORY_RESET_FINISHED,
  STATE_WRITING_STARTED,
  STATE_WRITING_FINISHED,
  STATE_BLE_CONNECTED,
  STATE_BLE_DISCONNECTED
};

enum {
  STATE_K380_CDC_ONLY = 100,
  STATE_K380_WRITE_FAILED,
  STATE_K380_POWER_REJECTED
};

void neopixel_write_pixels(const uint8_t *pixels, uint16_t pixel_count);

#endif
